version: '3.8'

services:
  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   image: hlexnc/devablos-project-v2-client
  #   platform: linux/amd64
  #   ports:
  #     - "3000:3000"

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: hlexnc/devablos-project-v2-server
    platform: linux/amd64
    ports:
      - "5000:5000"
      - "5001:5001"
