name: Build and deploy Node.js app to Azure Web App - devablos-server

on:
  push:
    branches:
      - feature/deployment-setup
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Set environment variables
        run: |
          echo "PORT=5000" >> server/.env
          echo "WS_PORT=5001" >> server/.env
          echo "CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}" >> server/.env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> server/.env
          echo "SSL_KEY_PATH=${{ secrets.SSL_KEY_PATH }}" >> server/.env
          echo "SSL_CERT_PATH=${{ secrets.SSL_CERT_PATH }}" >> server/.env

      - name: Install dependencies and build server
        run: |
          cd server
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: |
          cd server
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'devablos-server'
          package: .
