name: Build and Deploy Client App to Azure Web App

on:
  push:
    branches:
      - dev-client

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Set Environment Variables from .env.example
      run: |
        cp client/.env.example client/.env
        echo "PORT=${{ secrets.PORT }}" >> client/.env
        echo "REACT_APP_SERVER_URL=${{ secrets.REACT_APP_SERVER_URL }}" >> client/.env
        echo "REACT_APP_WS_URL=${{ secrets.REACT_APP_WS_URL }}" >> client/.env

    - name: Extract tag name
      id: tag_name
      run: echo "::set-output name=TAG_NAME::${GITHUB_REF#refs/heads/}"

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./client/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/devablos-client:${{ steps.tag_name.outputs.TAG_NAME }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'devablos-client'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        images: 'ghcr.io/${{ github.repository_owner }}/devablos-client:${{ steps.tag_name.outputs.TAG_NAME }}'
